<a href="https://colab.research.google.com/github/Anekantjainsagar/machineLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics

Fast operating n dimensional arrays

1. Using Lists

In [ ]:
import numpy as np

In [ ]:
list = [1,2,3]

In [ ]:
type(list)

list

In [ ]:
numpy_array = np.array(list)

In [ ]:
numpy_array

array([1, 2, 3])

In [ ]:
type(numpy_array)

numpy.ndarray

In [ ]:
my_matrix = [[1,2,3],[4,5,6]];

In [ ]:
numpy_matrix = np.array(my_matrix)

In [ ]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6]])

2. Using Built in functions

In [ ]:
random_arr = np.arange(0,10,1)

In [ ]:
random_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
random_arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
len(np.arange(0,10,0.5))

20

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0, 10, 11, False)
# 3rd will be how much length we want
# 4rth is last one to be included or not

array([0.        , 0.90909091, 1.81818182, 2.72727273, 3.63636364,
       4.54545455, 5.45454545, 6.36363636, 7.27272727, 8.18181818,
       9.09090909])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

3. Random distributions of data

In [ ]:
np.random.rand(2,4)
# 1 and 2 are shape where they'll return a random number between 0 and 1

array([[0.75752495, 0.51056207, 0.11147113, 0.16439958],
       [0.51959067, 0.19943108, 0.62717272, 0.53938504]])

In [ ]:
np.random.randint(0,100,(2,3))
# 1 and 2 are range of integers and third will be the size

array([[20, 35, 93],
       [40, 17, 70]])

In [ ]:
np.random.seed(42)
np.random.rand(4)
# Always return same numbers

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
random_int_arr = np.random.randint(0,101,10)

In [ ]:
random_int_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [ ]:
random_int_arr.max() # Max value
random_int_arr.argmax() # Max value index

5

In [ ]:
random_int_arr.min() # Min value
random_int_arr.argmin() # Min value index

7

In [ ]:
random_int_arr.dtype

dtype('int64')

In [ ]:
random_int_arr.shape

(10,)

# Indexing and Selection

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(11,100)

In [ ]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
       96, 97, 98, 99])

In [ ]:
arr[2]

13

In [ ]:
arr[1:3]

array([12, 13])

In [ ]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

In [ ]:
arr[:2]

array([11, 12])

In [ ]:
arr[0:50] = 500 # Changing all the items

In [ ]:
arr

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99])

In [ ]:
arr = np.arange(0,11,0.1)

In [ ]:
arr

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9])

In [ ]:
slice_arr = arr[0:5] # Works as a pointer

In [ ]:
slice_arr

array([0. , 0.1, 0.2, 0.3, 0.4])

In [ ]:
slice_arr[:] = 100

In [ ]:
slice_arr

array([100., 100., 100., 100., 100.])

In [ ]:
arr

array([100. , 100. , 100. , 100. , 100. ,   0.5,   0.6,   0.7,   0.8,
         0.9,   1. ,   1.1,   1.2,   1.3,   1.4,   1.5,   1.6,   1.7,
         1.8,   1.9,   2. ,   2.1,   2.2,   2.3,   2.4,   2.5,   2.6,
         2.7,   2.8,   2.9,   3. ,   3.1,   3.2,   3.3,   3.4,   3.5,
         3.6,   3.7,   3.8,   3.9,   4. ,   4.1,   4.2,   4.3,   4.4,
         4.5,   4.6,   4.7,   4.8,   4.9,   5. ,   5.1,   5.2,   5.3,
         5.4,   5.5,   5.6,   5.7,   5.8,   5.9,   6. ,   6.1,   6.2,
         6.3,   6.4,   6.5,   6.6,   6.7,   6.8,   6.9,   7. ,   7.1,
         7.2,   7.3,   7.4,   7.5,   7.6,   7.7,   7.8,   7.9,   8. ,
         8.1,   8.2,   8.3,   8.4,   8.5,   8.6,   8.7,   8.8,   8.9,
         9. ,   9.1,   9.2,   9.3,   9.4,   9.5,   9.6,   9.7,   9.8,
         9.9,  10. ,  10.1,  10.2,  10.3,  10.4,  10.5,  10.6,  10.7,
        10.8,  10.9])

In [ ]:
brr = slice_arr.copy()

In [ ]:
brr[:] = 5

In [ ]:
arr

array([100. , 100. , 100. , 100. , 100. ,   0.5,   0.6,   0.7,   0.8,
         0.9,   1. ,   1.1,   1.2,   1.3,   1.4,   1.5,   1.6,   1.7,
         1.8,   1.9,   2. ,   2.1,   2.2,   2.3,   2.4,   2.5,   2.6,
         2.7,   2.8,   2.9,   3. ,   3.1,   3.2,   3.3,   3.4,   3.5,
         3.6,   3.7,   3.8,   3.9,   4. ,   4.1,   4.2,   4.3,   4.4,
         4.5,   4.6,   4.7,   4.8,   4.9,   5. ,   5.1,   5.2,   5.3,
         5.4,   5.5,   5.6,   5.7,   5.8,   5.9,   6. ,   6.1,   6.2,
         6.3,   6.4,   6.5,   6.6,   6.7,   6.8,   6.9,   7. ,   7.1,
         7.2,   7.3,   7.4,   7.5,   7.6,   7.7,   7.8,   7.9,   8. ,
         8.1,   8.2,   8.3,   8.4,   8.5,   8.6,   8.7,   8.8,   8.9,
         9. ,   9.1,   9.2,   9.3,   9.4,   9.5,   9.6,   9.7,   9.8,
         9.9,  10. ,  10.1,  10.2,  10.3,  10.4,  10.5,  10.6,  10.7,
        10.8,  10.9])

In [ ]:
brr

array([5., 5., 5., 5., 5.])

In [ ]:
slice_arr

array([100., 100., 100., 100., 100.])

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

# New Section

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[1,2]

6

In [ ]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# Operations

# New Section

In [ ]:
arr = np.arange(0,50,10)

In [ ]:
arr

array([ 0, 10, 20, 30, 40])

In [ ]:
arr ** 3

array([    0,  1000,  8000, 27000, 64000])

In [ ]:
arr/arr

<ipython-input-83-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.])

In [ ]:
np.sqrt(arr)

array([0.        , 3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [ ]:
arr

array([ 0, 10, 20, 30, 40])

In [ ]:
arr.sum()

100

In [ ]:
arr.min()

0

In [ ]:
arr.mean()

20.0

In [ ]:
arr.std()

14.142135623730951

In [ ]:
arr.var()

200.0

In [ ]:
np.sin(arr)

array([ 0.        , -0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [ ]:
np.log(arr)

<ipython-input-92-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [ ]:
np.cos(arr)

array([ 1.        , -0.83907153,  0.40808206,  0.15425145, -0.66693806])

In [ ]:
arr.sum()

100

In [ ]:
arr.mean()

20.0

In [ ]:
arr2d = np.arange(0,25,1).reshape(5,5)

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d.sum()

300

In [ ]:
arr2d.mean()

12.0

In [ ]:
arr2d.std()

7.211102550927978

In [ ]:
arr2d.var()

52.0

In [ ]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])